<?php
$this->layout('../layouts/layout',[
    'title' => 'Xoluciones  | Clientes'
]);
?>

<?php $this->push('styles')?>
<!-- Estilos personalizados -->
<?php $this->end()?>

<?php $this->start('contents')?>
<!-- Contenido de la pagina -->
<div class="container">
<h1>Clientes</h1>
<br>
    <div class="row">
            <div class="col-sm-4">
                <a is-modal="true" href="<?= URL . 'cliente/detail' ?>" class="btn btn-primary btn-block">Nuevo</a>
            </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 5%">ID</th>
                        <th style="width: 15%">NOMBRES</th>
                        <th style="width: 15%">APELLIDOS</th>
                        <th style="width: 20%">DIRECCION</th>
                        <th style="width: 10%">TELEFONO</th>
                        <th style="width: 10%">CREDITO</th>
                        <th style="width: 10%">RUC</th>
                        <th style="width: 15%"></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach($data as $row): ?>
                        <tr>
                            <td><?= $row->IdCliente ?></td>
                            <td><?= $row->Nombres ?></td>
                            <td><?= $row->Apellidos ?></td>
                            <td><?= $row->Direccion ?></td>
                            <td><?= $row->Telf ?></td>
                            <td><?= $row->CreditoLimite ?></td>
                            <td><?= $row->Ruc ?></td>
                            <td>
                                <a is-modal="true" href="<?= URL . "cliente/detail/{$row->IdCliente}" ?>" class="btn btn-success btn-sm"><i class="fas fa-pencil-alt"></i></a>
                                <a name="cliente" id="delete_crud" href="<?= URL . "cliente/delete/{$row->IdCliente}" ?>" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
    <br>
</div>
<?php $this->stop()?>

<?php $this->start('myModal')?>
<?php
$title = 'Cliente Detalle - Insertar';
$size = MUYGRANDE;
include MAINPATH . 'app/views/layouts/partials/_modalGenerico.phtml'
?>
<?php $this->stop()?>

<?php $this->push('scripts')?>
<script src="<?=URL.'js/scripts/modal_crud.js'?>"></script>
<script src="<?=URL.'js/scripts/delete_crud.js'?>"></script>
<?php $this->end()?>