<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="<?= URL . 'categoria/save' ?>" method="post">
                <input type="hidden" name="idcateg" value="<?= $data->IdCateg ?>">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="nombre">Nombre</label>
                            <input placeholder="Nombre Categoria"  required pattern="[A-Za-z0-9]{5,50}"
                            title="Letras y números. Tamaño mínimo: 5. Tamaño máximo: 50" type="text" name="nombre" id="id_nombre" class="form-control" value="<?= $data->Nombre ?>">

                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="descripcion">Descripcion</label>
                            <input required placeholder="Descripción" pattern="[A-Za-z0-9]+{5,80}" title="Letras y números. Tamaño mínimo: 5. Tamaño máximo: 80" type="text" name="descripcion" id="id_descripcion" class="form-control" value="<?= $data->Descripcion ?>">

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group form-check">
                            <!-- <input type="checkbox" class="form-check-input" id="id_estado" <?= ($data->Estado == 1) ? true : false ?>> -->
                            <input type="checkbox" name="estado" class="form-check-input" id="id_estado" <?= ($data->Estado == 1) ? 'checked' : '' ?>>

                            <label class="form-check-label" for="id_estado" >Estado</label>
                        </div>

                    </div>
                        
                    <div class="col-sm-8">
                    </div>
                </div>
                <br><br>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Guardar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>