<?php
$this->layout('../layouts/layout',[
    'title' => 'Xoluciones  | Categorías'
]);
?>

<?php $this->push('styles')?>
<!-- Estilos personalizados -->
<?php $this->end()?>

<?php $this->start('contents')?>
<!-- Contenido de la pagina -->
<div class="container">
    <h1>Categorias</h1>
    <div class="row">
            <div class="col-sm-4">
                <a is-modal="true" href="<?= URL . 'categoria/detail' ?>" class="btn btn-primary btn-block">Nuevo</a>
            </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 10%">ID</th>
                        <th style="width: 30%">NOMBRE</th>
                        <th style="width: 40%">DESCRIPCIÓN</th>
                        <th style="width: 20%"></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach($data as $row): ?>
                        <tr>
                            <td><?= $row->IdCateg ?></td>
                            <td><?= $row->Nombre ?></td>
                            <td><?= $row->Descripcion ?></td>
                            <td>
                                <a is-modal="true" href="<?= URL . "categoria/detail/{$row->IdCateg}" ?>" class="btn btn-success btn-sm"><i class="fas fa-pencil-alt"></i></a>
                                <a name="Categoria" id="delete_crud" href="<?= URL . "categoria/delete/{$row->IdCateg}" ?>" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
    <br>
</div>
<?php $this->stop()?>

<?php $this->start('myModal')?>
<?php
$title = 'Categoria Detalle - Insertar';
$size = MUYGRANDE;
include MAINPATH . 'app/views/layouts/partials/_modalGenerico.phtml'
?>
<?php $this->stop()?>

<?php $this->push('scripts')?>
<script src="<?=URL.'js/scripts/modal_crud.js'?>"></script>
<script src="<?=URL.'js/scripts/delete_crud.js'?>"></script>
<?php $this->end()?>