<?php
$this->layout('../layouts/layout', [
    'title' => 'IVAVENTAS | REGISTRARSE'
]);
?>

<?php $this->push('styles') ?>
<!-- Estilos personalizados -->
<?php $this->end() ?>

<?php $this->start('contents') ?>

<!-- Contenido de la pagina -->
<?php include MAINPATH . 'app/views/layouts/partials/_areaRegister.phtml' ?>

<?php $this->stop() ?>

<?php $this->push('scripts') ?>
<!-- Scripts personalizados -->
<?php $this->end() ?>