<!-- banner area two start -->
<!-- <div class="banner-area-two">
    <div class="container">
        <div class="row no-gutters">
            <div class="col-lg-6 col-xl-6">
                <div class="banner-wrapper mrgn-r-4">
                    <a href="#"><img src="<?= URL . 'img/banner/4.jpg' ?>" alt=""></a>
                    <div class="banner-wrapper-content">
                        <h3>20% <br><span>off</span></h3>
                        <h2><span>Trending</span> <br>Fashion <br>2018...</h2>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-6">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        <div class="banner-wrapper mrgn-b-4">
                            <a href="#"><img src="<?= URL . 'img/banner/5.jpg' ?>" alt=""></a>
                            <div class="banner-wrapper-content2">
                                <h3>Winter <br>Collection.</h3>
                                <a href="#">shop now</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="row no-gutters">
                            <div class="col-lg-6">
                                <div class="banner-wrapper mrgn-r-4">
                                    <a href="#"><img src="<?= URL . 'img/banner/6.jpg' ?>" alt=""></a>
                                    <div class="banner-wrapper-content3">
                                        <h3><span>new</span> <br>fashion</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="banner-wrapper">
                                    <a href="#"><img src="<?= URL . 'img/banner/7.jpg' ?>" alt=""></a>
                                    <div class="banner-wrapper-content4">
                                        <h4>25 December.</h4>
                                        <h2>Gift Shop</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->
<!-- banner area two end -->