<div class="block-slideshow block-slideshow--layout--with-departments block">
    <div class="container">
        <br>
        <!-- <h4>BIENVENIDOS A LA FERRETERIA DDYES</h4> -->
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active"">
                    <img src=" images/slides/slide-1-full.jpg" class="d-block w-100" alt="...">
                    <div class="block-slideshow__slide-content">
                        <div class="block-slideshow__slide-title">Big choice of<br>Plumbing products
                        </div>
                        <div class="block-slideshow__slide-text">Lorem ipsum dolor sit amet,
                            consectetur adipiscing elit.<br>Etiam pharetra laoreet dui quis
                            molestie.</div>
                        <div class="block-slideshow__slide-button"><span class="btn btn-primary btn-lg">Shop Now</span></div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="images/slides/slide-2-full.jpg" class="d-block w-100" alt="...">
                    <div class="block-slideshow__slide-content">
                        <div class="block-slideshow__slide-title">Big choice of<br>Plumbing products
                        </div>
                        <div class="block-slideshow__slide-text">Lorem ipsum dolor sit amet,
                            consectetur adipiscing elit.<br>Etiam pharetra laoreet dui quis
                            molestie.</div>
                        <div class="block-slideshow__slide-button"><span class="btn btn-primary btn-lg">Shop Now</span></div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="images/slides/slide-3-full.jpg" class="d-block w-100" alt="...">
                    <div class="block-slideshow__slide-content">
                        <div class="block-slideshow__slide-title">Big choice of<br>Plumbing products
                        </div>
                        <div class="block-slideshow__slide-text">Lorem ipsum dolor sit amet,
                            consectetur adipiscing elit.<br>Etiam pharetra laoreet dui quis
                            molestie.</div>
                        <div class="block-slideshow__slide-button"><span class="btn btn-primary btn-lg">Shop Now</span></div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    </div>
</div>