<!doctype html>
<html class="no-js" lang="zxx">

<!-- index-431:41-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?= $this->e($title) ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <?= $this->section('styles') ?>
    <link rel="icon" type="image/png" href="<?= URL . 'images/favicon.png' ?>"><!-- fonts -->    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i"><!-- css -->
    <link rel="stylesheet" href="<?= URL . 'js/vendor/bootstrap-4.2.1/css/bootstrap.min.css' ?>">
    <link rel="stylesheet" href="<?= URL . 'js//owl-carousel-2.3.4/assets/owl.carousel.min.css' ?>">
    <link rel="stylesheet" href="<?= URL . 'css/style.css' ?>"><!-- js -->
    <script src="<?= URL . 'js/vendor/jquery-3.3.1/jquery.min.js' ?>"></script>
    <script src="<?= URL . 'js/vendor/bootstrap-4.2.1/js/bootstrap.bundle.min.js' ?>"></script>
    <script src="<?= URL . 'js/vendor/owl-carousel-2.3.4/owl.carousel.min.js' ?>"></script>
    <script src="<?= URL . 'js/vendor/nouislider-12.1.0/nouislider.min.js' ?>"></script>
    <link rel="stylesheet" href="<?= URL . 'css/material-design-iconic-font.min.css' ?>">
    <link rel="stylesheet" href="<?= URL . 'css/font-awesome.min.css' ?>">
    <link rel="stylesheet" href="<?= URL . 'css/fontawesome-stars.css' ?>">
    <script src="<?= URL . 'js/vendor/svg4everybody-2.1.9/svg4everybody.min.js' ?>"></script>
    <script>svg4everybody();</script><!-- font - fontawesome -->
    <link rel="stylesheet" href="<?= URL . 'js/vendor/fontawesome-5.6.1/css/all.min.css' ?>"><!-- font - stroyka -->
    <link rel="stylesheet" href="<?= URL . 'fonts/stroyka/stroyka.css' ?>">
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-97489509-6"></script>
    <script>window.dataLayer = window.dataLayer || []; function gtag() { dataLayer.push(arguments); } gtag('js', new Date()); gtag('config', 'UA-97489509-6');</script>
</head>

<body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
    <!-- Begin Body Wrapper -->
    <div class="body-wrapper">

        <?php include MAINPATH . 'app/views/layouts/partials/_header.phtml' ?>

        <?= $this->section('contents') ?>

        <?php include MAINPATH . 'app/views/layouts/partials/_footer.phtml' ?>

    </div>

    <?= $this->section('myModal') ?>
    <!-- SweetAlert2 -->
    <script src="<?= URL . 'js/sweetalert/sweetalert2.all.min.js' ?>"></script>
    <script src="js/number.js"></script>
    <script src="js/main.js"></script>
    <?= $this->section('scripts') ?>
</body>

<!-- index-431:47-->

</html>