<!doctype html>
<html class="no-js" lang="zxx">

<!-- index-431:41-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?= $this->e($title) ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <?= $this->section('styles') ?>
    <link rel="icon" type="image/png" href="<?= URL . 'images/favicon.png' ?>"><!-- fonts -->    
    <!-- all css here -->
    <link rel="stylesheet" href="<?= URL . 'css/bootstrap.min.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/magnific-popup.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/animate.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/owl.carousel.min.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/themify-icons.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/pe-icon-7-stroke.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/meanmenu.min.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/bundle.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/style.css'?>">
    <link rel="stylesheet" href="<?= URL . 'css/responsive.css'?>">
    <script src="<?= URL . 'js/vendor/modernizr-2.8.3.min.js'?>"></script>
</head>

<body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
    <!-- Begin Body Wrapper -->
    <div class="body-wrapper">

        <?php include MAINPATH . 'app/views/layouts/partials/_header.phtml' ?>

        <?= $this->section('contents') ?>

        <?php include MAINPATH . 'app/views/layouts/partials/_footer.phtml' ?>

    </div>

    <?= $this->section('myModal') ?>
    <!-- SweetAlert2 -->
    <script src="<?= URL . 'js/sweetalert/sweetalert2.all.min.js' ?>"></script>
    <!-- all js here -->
    <script src="<?= URL . 'js/vendor/jquery-1.12.0.min.js'?>"></script>
    <script src="<?= URL . 'js/popper.js'?>"></script>
    <script src="<?= URL . 'js/bootstrap.min.js'?>"></script>
    <script src="<?= URL . 'js/jquery.magnific-popup.min.js'?>"></script>
    <script src="<?= URL . 'js/isotope.pkgd.min.js'?>"></script>
    <script src="<?= URL . 'js/imagesloaded.pkgd.min.js'?>"></script>
    <script src="<?= URL . 'js/jquery.counterup.min.js'?>"></script>
    <script src="<?= URL . 'js/waypoints.min.js'?>"></script>
    <script src="<?= URL . 'js/ajax-mail.js'?>"></script>
    <script src="<?= URL . 'js/owl.carousel.min.js'?>"></script>
    <script src="<?= URL . 'js/plugins.js'?>"></script>
    <script src="<?= URL . 'js/main.js'?>"></script>
    <?= $this->section('scripts') ?>
</body>

<!-- index-431:47-->

</html>